### ISSUE TITLE
Losing Red Color

### ISSUE THREAD

**Issue by gfiumara** [biometricITC/Vein-Toolbox#3]
In Overview:
> The TOE can also capture the vein image with visible light and vein patterns appear as those lines losing red color component in the image.

I admittedly know nothing about vein biometrics, but I'm not sure what is implied here by "losing red color component" to know how to suggest a change to this sentence. Does it mean that the vein patterns appear as primarily as mixtures of the green and blue components?

**Comment by n-kai** [comment]
The vein pattern can be appeared as primarily as mixture of the green and red color components. Deoxidised haemoglobin in vein absorbs red light (so intensity of red color is decreased), making the vein pattern dark however blue light which is a shorter wavelength doesn’t penetrate so far into the skin and mostly deflected back (so blue color component doesn't include much information about the vein).

Is the following text more clearer for you? (or you can suggest any better text)
**The TOE can also capture the vein image with visible light and vein patterns appear as those lines losing red color component in the image because haemoglobin in vein absorbs red light making the vein pattern visible.**

**Comment by gfiumara** [comment]
Ah, I understand better now. The extra detail in the sentence is helpful, but I think the primary change I would make would be changing "losing" to "lacking" or "with a limited."

**Comment by woodbe** [comment]
Closing as part of merged update
